[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableStaticServing = true
runOnSave = true
allowRunOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[global]
developmentMode = false
logLevel = "info"
unitTest = false
suppressDeprecationWarnings = true
disableWatchdogWarning = true 