# Copy this file and add your actual API key
# 复制此文件并添加您的实际API密钥

[secrets]
GEMINI_API_KEY = "GEMINI_API_KEY"

# Optional: Additional API keys for future extensions
# 可选：为未来扩展准备的其他API密钥
# OPENAI_API_KEY = "your_openai_key"
# ANTHROPIC_API_KEY = "your_anthropic_key" 